version: "3"

dotenv: [".env"]

tasks:
  on:
    cmds:
      - docker compose up -d --build
      - docker compose exec app /bin/bash

  off:
    cmd: docker compose down

  dev:
    cmd: air -c .air.toml

  build:
    deps:
      - clean
      - gen-db
      - gen-css
    cmds:
      - task fmt
      - go build -o ./dist/app ./cmd/app/.

  serve:
    cmd: ./dist/app

  migrate-serve:
    cmds:
      - task goose -- up
      - task serve

  run:
    cmds:
      - task build
      - task serve

  goose:
    cmd: eval $(go run ./cmd/goose/. {{.CLI_ARGS}})

  gen-db:
    cmd: sqlc generate

  reset-db:
    cmd: go run ./cmd/resetdb/.

  gen-css:
    cmd: >
      npm run tailwindcss --
      --config ./tailwind.config.js
      --input ./internal/view/static/css/tailwind.css
      --output ./internal/view/static/css/style.css --minify

  tidy:
    cmd: go mod tidy

  fmt:
    cmds:
      - go fmt ./...
      - npm run standard

  lint-only:
    cmds:
      - task gen-db
      - golangci-lint run ./...

  test-only:
    cmds:
      - task gen-db
      - go test ./...

  test:
    cmds:
      - task lint-only
      - task test-only

  clean:
    cmds:
      - rm -rf ./tmp
      - rm -rf ./dist

  fixperms: # Fixes the permissions of the files in the project
    cmd: ./scripts/fixperms.sh
