name: Sync README

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  run_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync Docker Hub README
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          repository: eduardolat/pgbackweb
          readme: "./README.md"
