name: Sync README

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  run_sync:
    name: Sync
    uses: ms-jpq/sync-dockerhub-readme@v1
    with:
      username: ${{ secrets.DOCKERHUB_USER }}
      password: ${{ secrets.DOCKERHUB_PASS }}
      repository: eduardolat/pgbackweb
      readme: "./README.md"
